import dimensional_compactification_quantum_field_theory_foundation_canonical_lane_mathlib.GateLemmas
import dimensional_compactification_quantum_field_theory_foundation_canonical_lane_mathlib.FinalTheorem
